# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: adb493ab755326017d1f3ced718ea0e12fd40d1c33a70dec5aec21ec7afc2e760ebee8fad6a4747ed47ca6e47685d0c5da82faa2401bfa2545ff0e89b06cb7c0
  facebook_key: 1016592088409548
  facebook_secret: e61a163aa45cb4def2a83917745f980d
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_mailer_access_key_id: <%= ENV["AWS_MAILER_ACCESS_KEY_ID"] || ENV["AWS_ACCESS_KEY_ID"]%>
  aws_mailer_secret_access_key: <%= ENV["AWS_MAILER_SECRET_ACCESS_KEY"] || ENV["AWS_SECRET_ACCESS_KEY"]%>

test:
  secret_key_base: 6bf84fe515fd3890064dd8fb310c12c3f5c1141a2fbe7235053dbc214260b66d7b904613271b9e8818519a6610fbab59ef5879dd1933bdf51879cc1f0d1cad30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_key: 1016592088409548
  facebook_secret: e61a163aa45cb4def2a83917745f980d
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_mailer_access_key_id: <%= ENV["AWS_MAILER_ACCESS_KEY_ID"] || ENV["AWS_ACCESS_KEY_ID"]%>
  aws_mailer_secret_access_key: <%= ENV["AWS_MAILER_SECRET_ACCESS_KEY"] || ENV["AWS_SECRET_ACCESS_KEY"]%>
